"""initial migration

Revision ID: 741a18f4c06a
Revises: 
Create Date: 2025-07-15 17:57:41.135210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741a18f4c06a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocodes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('reward_type', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uses_left', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('quest_type', sa.String(length=20), nullable=True),
    sa.Column('reward_type', sa.String(length=20), nullable=True),
    sa.Column('reward_value', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('coins', sa.BigInteger(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('max_energy', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('total_clicks', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by', sa.String(length=16), nullable=True),
    sa.Column('milestone_5_friends_claimed', sa.Boolean(), nullable=False),
    sa.Column('reward_5_friends_claimed', sa.Boolean(), nullable=False),
    sa.Column('reward_10_friends_claimed', sa.Boolean(), nullable=False),
    sa.Column('youtube_subscribed', sa.Boolean(), nullable=False),
    sa.Column('youtube_reward_claimed', sa.Boolean(), nullable=False),
    sa.Column('youtube_timer_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_subscribed', sa.Boolean(), nullable=False),
    sa.Column('telegram_reward_claimed', sa.Boolean(), nullable=False),
    sa.Column('telegram_timer_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('boost_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('boost_multiplier', sa.Integer(), nullable=False),
    sa.Column('last_energy_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('last_daily_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('genshin_balance', sa.Integer(), nullable=False),
    sa.Column('honkai_balance', sa.Integer(), nullable=False),
    sa.Column('zenless_balance', sa.Integer(), nullable=False),
    sa.Column('locked_coins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('exchange_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('received_amount', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_requests')
    op.drop_table('users')
    op.drop_table('quests')
    op.drop_table('promocodes')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
